title: "Yuta Takahashi"
name: "Yuta Takahashi"
description: "Associate Professor (without tenure), Institute of Social and Economic Research, the University of Osaka"
email: "yuta.takahashi@iser.osaka-u.ac.jp"
address: "6-1 Mihogaoka, Ibaraki, Osaka 567-0047, Japan"
last_updated: "2025/08/16"

url: "https://yuta-takahashi-1211.github.io"
baseurl: ""   # ← 追加
repository: "yuta-takahashi-1211/yuta-takahashi-1211.github.io"
# baseurl はユーザーサイトでは空/未指定が正解（指定しない）

# 著者情報（テーマが参照するキー）
author:
  name: "Yuta Takahashi"
  avatar: "https://yuta-takahashi-1211.github.io/assets/images/IMG_0156_edited.jpg"
  bio: "Macroeconomics"
  location: "Osaka, Japan"
  links:
    - label: "Email"
      url: "mailto:yuta.takahashi@iser.osaka-u.ac.jp"

# 互換性のため owner も定義（派生レイアウト対策）
owner:
  name: "Yuta Takahashi"
  avatar: "/assets/images/IMG_0156_edited.jpg"
  bio: "Macroeconomics"
  location: "Osaka, Japan"

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-remote-theme
  # sitemap / feed は入れていない（フッターに出したくないため）

# _pages ディレクトリを使う
include:
  - _pages

# _pages 配下の既定設定
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Sass（カスタムCSSを効かせるため）
sass:
  style: compressed

# フッターのリンクを空に（Sitemap, Feed を非表示）
footer:
  links: []

minimal_mistakes_skin: "air" 
# 他に: "plum" "mint" "sunrise" "aqua" など
