title: "Yuta Takahashi"
name: "Yuta Takahashi"
description: "Associate Professor (without tenure), Institute of Social and Economic Research, the University of Osaka"
email: "yuta.takahashi@iser.osaka-u.ac.jp"
address: "6-1 Mihogaoka, Ibaraki, Osaka 567-0047, Japan"
last_updated: "2025/08/16"

url: "https://yuta-takahashi-1211.github.io"
repository: "yuta-takahashi-1211/yuta-takahashi-1211.github.io"

author:
  name: "Yuta Takahashi"
  avatar: "/assets/images/IMG_0156_edited.jpg"
  bio: "Macroecnomics"
  location: "Osaka, Japan"
  links:
    - label: "Email"
      url: "mailto:yuta.takahashi@iser.osaka-u.ac.jp"

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-remote-theme

